/* =========================================================
   Rebuilds sitemap.xml from js/products.js.

   Run it yourself:   node tools/build-sitemap.mjs
   Or let GitHub run it: .github/workflows/sitemap.yml does this
   automatically every time you push a change to products.js.

   The domain comes from the CNAME file if you've set a custom
   domain, otherwise it falls back to the placeholder below.
   ========================================================= */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const FALLBACK_DOMAIN = "YOUR-DOMAIN.co.uk";
const PAGES = ["index.html", "shop.html", "about.html", "quality.html", "coa.html",
               "disclaimer.html", "faq.html", "contact.html", "shipping.html",
               "returns.html", "terms.html", "privacy.html", "cookies.html"];

const domain = existsSync("CNAME")
  ? readFileSync("CNAME", "utf8").trim().replace(/^https?:\/\//, "").replace(/\/$/, "")
  : FALLBACK_DOMAIN;

const src = readFileSync("js/products.js", "utf8");
const ids = [...src.matchAll(/\n\s{4}id:\s*"([^"]+)"/g)].map(m => m[1]);
if (!ids.length) {
  console.error("No product ids found in js/products.js — sitemap not written.");
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);
const url = path => `  <url><loc>https://${domain}/${path}</loc><lastmod>${today}</lastmod></url>`;

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schema/sitemap/0.9">',
  "  <!-- Generated by tools/build-sitemap.mjs — do not edit by hand -->",
  ...PAGES.map(url),
  ...ids.map(id => url(`product.html?id=${id}`)),
  "</urlset>", ""
].join("\n");

writeFileSync("sitemap.xml", xml);
console.log(`sitemap.xml written — ${PAGES.length} pages, ${ids.length} products, domain ${domain}`);
